# Generated by Django 3.1.3 on 2020-11-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('level', models.IntegerField()),
                ('abilityType', models.CharField(choices=[('Arcane Spell', 'Arcane Spell'), ('Divine Spell', 'Divine Spell'), ('Feat', 'Feat')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AbilityUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1)),
                ('abilities', models.ManyToManyField(to='api.Ability')),
                ('characterClass', models.ManyToManyField(to='api.CharacterClass')),
            ],
        ),
    ]
