# Generated by Django 3.1.3 on 2020-11-07 16:01

from django.db import migrations

def seedCharacters(apps, schema_editor):
    User = apps.get_model('userAuth', 'User')
    Character = apps.get_model('api', 'Character')
    CharacterClass = apps.get_model('api', 'CharacterClass')
    seedCharacter = Character(name='Seed Character', level=1, player=User.objects.get(email='seeduseremail'))
    seedCharacter.save()
    seedCharacter.characterClass.add(CharacterClass.objects.get(name='Wizard'))
    

def seedCharacterClasses(apps, schema_editor):
    CharacterClass = apps.get_model('api', 'CharacterClass')
    CLASSES = [
        'Cleric',
        'Wizard',
        'Fighter'
    ]
    for className in CLASSES:
        seedClass = CharacterClass(name=className)
        seedClass.save()


def seedAbilities(apps, schema_editor):
    Ability = apps.get_model('api', 'Ability')
    seedAbility = Ability(name='Seed Ability', description='Seed Description', level=1, abilityType='Arcane Spell') 
    seedAbility.save()

# Seeds the database with dummy data.
class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201112_2004'),
        ('userAuth', '0002_seed_one_user'),
    ]

    operations = [
        migrations.RunPython(seedCharacterClasses),
        migrations.RunPython(seedAbilities),
        migrations.RunPython(seedCharacters),
    ]
