# Generated by Django 3.1.3 on 2020-12-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201204_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
