# Generated by Django 3.1.3 on 2020-12-04 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_auto_20201204_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('currentCharacter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.character')),
                ('currentGameSession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gamesession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
