# Generated by Django 3.1.3 on 2020-12-04 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201204_1513'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentCharacter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.character')),
                ('currentGameSession', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.gamesession')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
