# Generated by Django 3.1.3 on 2020-11-12 20:07

from django.db import migrations


def seedUsers(apps, schema_editor):
    User = apps.get_model('userAuth', 'User')
    seedUser = User(username='seedusername', email='seeduseremail', password='Test Hash')
    seedUser.save()

class Migration(migrations.Migration):

    dependencies = [
        ('userAuth', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seedUsers)
    ]
